version: "3.8"

services:
    #frontend
  frontend1:
    image: tomas-manriquez/frontend:latest
    networks:
      - frontend-network

  frontend2:
    image: tomas-manriquez/frontend:latest
    networks:
      - frontend-network

  frontend3:
    image: tomas-manriquez/frontend:latest
    networks:
        - frontend-network
  #backend
  backend1:
    image: tomas-manriquez/demo:latest
    environment:
      - DB_HOST=158.170.2.91
    networks:
      - backend-network

  backend2:
    image: tomas-manriquez/demo:latest
    environment:
      - DB_HOST=158.170.2.91
    networks:
      - backend-network

  backend3:
    image: tomas-manriquez/demo:latest
    environment:
      - DB_HOST=158.170.2.91
    networks:
      - backend-network

  #frontload balancing
  nginx-frontend:
    image: nginx:latest
    ports:
      - "8070:80"
    #volumen de persistencia en caso de que se caiga el container
    volumes:
    #uso de archivo en disco 'nginx-frontend.conf'
      - ./nginx-frontend.conf:/etc/nginx/nginx.conf
    depends_on:
      - frontend1
      - frontend2
      - frontend3
    networks:
      - frontend-network

  #backload balancing
  nginx-backend:
    image: nginx:latest
    ports:
      - "8080:8080"
    volumes:
      - ./nginx-backend.conf:/etc/nginx/nginx.conf
    depends_on:
      - backend1
      - backend2
      - backend3
    networks:
      - backend-network

networks:
  frontend-network:
  backend-network: